POST  http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbmVtaWVzIiwiaWQiOiI2NTIxMDFlMGI5ZjA5NjBjM2M5NGEzOTAiLCJpYXQiOjE2OTY2NjI3MDh9.nJke-ElsD-YEOk52vbAj2R2VY2QpDUTui_bthdGCjB8

{
    "title": "Mongo",
    "author": "Kerkko",
    "url": "testi url",
    "likes": 2
}
 